### ISSUE TITLE
No ha sido posible ejecutar el código

### ISSUE THREAD

**Issue by jcarpio** [FranBeltranM/Proyecto_LSystem#1]
Debería añadir la información necesaria en el fichero README.md para poder ejecutar el proyecto

**Comment by FranBeltranM** [comment]
Buenas Jose,

¿Qué clase de problema le presenta al ejecutarlo? ¿Ha instalado la dependencia que se indica al principio del README.MD?

**Comment by FranBeltranM** [comment]
Lleva razón, después de discutirlo con mi compañero Manuel Jesús nos hemos percatado que al descargar el código le genera una carpeta Proyecto_LSystem-master:
![image](https://user-images.githubusercontent.com/61682172/87323822-93154180-c52f-11ea-984c-7ef28373d0a1.png)

En processing el main file tiene que llamarse igual que la carpeta, por eso le da error, renombre la carpeta a Proyecto_LSystem y debería poder ejecutarlo sin problema.

Saludos

**Comment by jcarpio** [comment]
Exactamente, ese ha sido el problema. Si se descarga el .zip hay que renombrar la carpeta. No estaría mal añadir este comentario en el README.md para facilitar la tarea a quien quiera probar vuestro código. Saludos
